Update system to handle recent uW server movements; fix lost text after exclamation marks
unfoldingWord-dev/obs-pdf pull request #2
Opened 2019-07-14 21:23 UTC by RobH123

Also handles recent uW branding changes.

Does already contain a little bit of extra unused code that will soon be used to upload the PDF files to AWS S3.

2019-07-15 02:14 UTC, RobH123 commented
Oh, it's automatically appended my latest commits. (I only intended the PR to cover the first 13 commits -- which get the system working as before = returning the created PDF. The later commits upload the created PDF to S3 instead.) I guess I need to learn a bit more about Github.

2019-07-15 11:56 UTC, jag3773 commented on AWS-README.md
> +docker run --name obs-pdf --rm -p 8080:80 -i -t unfoldingWord/obs-pdf:latest bash
I see the base image on Docker hub but I don't see https://hub.docker.com/r/unfoldingword/obs-pdf there...

2019-07-15 12:15 UTC, jag3773 commented on public/lib/pdf_from_dcs.py
> +            s3_commit_key = f'obs/auto_PDFs/{pdf_desired_name}'
Per slack thread, don't put them here.  Use Option 2 listed in https://github.com/unfoldingWord-dev/door43.org/issues/389

2019-07-15 12:18 UTC, jag3773 commented on resources/docker-app/README.md
> +docker run --name obs-pdf -p 8080:80 -dit --cpus=0.5 --restart unless-stopped unfoldingWord/obs-pdf:latest
We don't want the `--cpus` flag on these.  If you want to reduce the CPU share that it has then I'd suggest using `--cpu-shares` and set it to a number lower than 1024, maybe 768 or 512.

2019-07-16 12:02 UTC, phillip-hopper commented on public/lib/aws_tools/s3_handler.py
> +    # def get_object(self, key):
I'm guessing this was copied from another project. I would just remove the methods that are commented out, that way the next person isn't trying to figure out if they are part of a feature that hasn't been implemented yet.

2019-07-16 12:39 UTC, phillip-hopper requested changes

2019-07-16 12:39 UTC, phillip-hopper commented on public/lib/obs/obs_classes.py
> +
PyCharm/IntelliJ complains loudly about the extra white space.
![image](https://user-images.githubusercontent.com/5262964/61294366-a5855f80-a7a3-11e9-8040-c6b879e87ecd.png)

2019-07-16 12:39 UTC, phillip-hopper commented on public/lib/obs/obs_tex_export.py
> +        img_link = join_url_parts(OBSTexExport.api_url_jpg, res, f'obs-{fid}.jpg')
It looks like this change does nothing.

2019-12-17 04:08 UTC, closed without merging